service: commitment

provider:
    name: aws
    region: us-east-1

plugins:
    - ./vendor/bref/bref

custom:
    stage: ${opt:stage}
    domains:
        live: wtc.wanderingcrow.net
        dev: dev-wtc.wanderingcrow.net

functions:
    default:
        handler: index.php
        description: ''
        runtime: ${bref:layer.php-81-fpm}
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            -   httpApi: '/index'
    text:
        handler: index_text.php
        description: ''
        runtime: ${bref:layer.php-81-fpm}
        timeout: 28
        events:
            -   httpApi: '/text'

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
